version: '2'

services:
  axobase-app:
    env_file:
      - .env-dev
    volumes:
      - .:/go/src/axobase
      - ./scripts:/scripts
      - ./data:/axobase/data
      - ./papers:/axobase/papers
    ports:
      - 9100:9100
    entrypoint: ["revel", "run", "axobase"]